[project]
name = "drone"
version = "2.0.0"
description = "A reinforcement learning based drone controller and simulator"
authors = [
    { name = "Sam Turner", email = "sam@tensaur.ai" },
    { name = "Finlay Sanders", email = "fin@tensaur.ai" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cfclient>=2025.9",
]
